### ISSUE TITLE
colons in capture bonk

### ISSUE THREAD

**Issue by hvanderson** [dhruvasagar/vim-dotoo#12] opened 2015-03-23 16:42 UTC
it seems we can't use colons in the capture text....

**Comment by dhruvasagar** [comment] 2015-03-23 17:16
Just colons ? Did you get an error ? What's the output of `verb imap :` ?

**Comment by dhruvasagar** [comment] 2015-03-24 13:05
I can't reproduce this, I am able to use colons in the capture text. Kindly provide more information.

**Comment by hvanderson** [comment] 2015-03-24 13:15
ok! I will.
Hans Anderson, Advanced Technology, ESPN




On Mar 24, 2015, at 9:05 AM, Dhruva Sagar <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't reproduce this, I am able to use colons in the capture text. Kindly provide more information.

**Comment by hvanderson** [comment] 2015-03-24 14:31
Good morning! here is what I see, attempting g-C, “test with:”
[cid:EDCC01DD-27F9-4C6E-873F-536B257AFCFC@corp.espn.pvt]
Hans Anderson, Advanced Technology, ESPN




On Mar 24, 2015, at 9:05 AM, Dhruva Sagar <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't reproduce this, I am able to use colons in the capture text. Kindly provide more information.

**Comment by dhruvasagar** [comment] 2015-03-24 14:32
What did you modify exactly ? Did you add a new capture template ? Or are you talking about the capture buffer where you actually capture a headline ?

**Comment by hvanderson** [comment] 2015-03-24 14:39
this is out-of-the-box… no custom template. That was using the capture buffer for new todo ( “g-C”)
Hans Anderson, Advanced Technology, ESPN




On Mar 24, 2015, at 10:32 AM, Dhruva Sagar <notifications@github.com<mailto:notifications@github.com>> wrote:


What did you modify exactly ? Did you add a new capture template ? Or are you talking about the capture buffer where you actually capture a headline ?

**Comment by hvanderson** [comment] 2015-03-25 15:09
Hi, Dhruva! Here you have my vimrc and at the top, a list of pathogen’d plugins:

""plugins as of 2015/3/5...
"
".vim/bundle
"├── ctrlp.vim
"├── dotoo.vim
"├── gundo
"├── nerdtree
"├── rainbow_parentheses.vim
"├── tmuxline.vim
"├── vim-airline
"├── vim-bufferline
"├── vim-classpath
"├── vim-clojure-highlight
"├── vim-clojure-static
"├── vim-colors-solarized
"├── vim-dispatch
"├── vim-fireplace
"├── vim-fugitive
"├── vim-leiningen
"├── vim-projectionist
"├── vim-repeat
"├── vim-sensible
"├── vim-sexp
"├── vim-sexp-mappings-for-regular-people
"├── vim-speeddating
"├── vim-surround
"└── vim-yaml
"


"set the linewidth mark color to black
highlight ColorColumn ctermbg=0

"Use Vim settings, rather then Vi settings (much better!).
"This must be first, because it changes other options as a side effect.
set nocompatible

"activate pathogen
call pathogen#infect()

"allow backspacing over everything in insert mode
set backspace=indent,eol,start

"store lots of :cmdline history
set history=1000

set showcmd     "show incomplete cmds down the bottom
set showmode    "show current mode down the bottom

set number      "show line numbers

"display tabs and trailing spaces
set list
set listchars=tab:▷⋅,trail:⋅,nbsp:⋅

set incsearch   "find the next match as we type the search
set hlsearch    "hilight searches by default

set wrap        "dont wrap lines
set linebreak   "wrap lines at convenient points

if v:version >= 703
    "undo settings
    set undodir=~/.vim/undofiles
    set undofile

    set colorcolumn=+1 "mark the ideal max text width
endif

"default indent settings
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent

"folding settings
set foldmethod=indent   "fold based on indent
set foldnestmax=3       "deepest fold is 3 levels
set nofoldenable        "dont fold by default

set wildmode=list:longest   "make cmdline tab completion similar to bash
set wildmenu                "enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.o,*.obj,*~ "stuff to ignore when tab completing

set formatoptions-=o "dont continue comments when pushing o/O

"vertical/horizontal scroll off settings
set scrolloff=3
set sidescrolloff=7
set sidescroll=1

"load ftplugins and indent files
filetype plugin on
filetype indent on

"turn on syntax highlighting
syntax on

"some stuff to get the mouse going in term
set mouse=a
set ttymouse=xterm2
set mousemodel=extend

"automatically send file changes
set autoread

"smoother changes?
set ttyfast

"auto save when switching buffs
set autowrite

"tell the term has 256 colors
set t_Co=256

"hide buffers when not displayed
set hidden

"colors
set background=dark
colorscheme solarized

"yaml
au BufNewFile,BufRead *.protein,*.yaml,*.yml so .vim/bundle/vim-yaml/after/syntax/yaml.vim

"rainbow parens"
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces
let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue3'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgray',    'DarkOrchid3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['gray',        'RoyalBlue3'],
    \ ]

"statusline setup
set statusline =%#identifier#
set statusline+=[%t]    "tail of the filename
set statusline+=%*

"display a warning if fileformat isnt unix
set statusline+=%#warningmsg#
set statusline+=%{&ff!='unix'?'['.&ff.']':''}
set statusline+=%*

"display a warning if file encoding isnt utf-8
set statusline+=%#warningmsg#
set statusline+=%{(&fenc!='utf-8'&&&fenc!='')?'['.&fenc.']':''}
set statusline+=%*

set statusline+=%h      "help file flag
set statusline+=%y      "filetype

"read only flag
set statusline+=%#identifier#
set statusline+=%r
set statusline+=%*

"modified flag
set statusline+=%#identifier#
set statusline+=%m
set statusline+=%*

set statusline+=%{fugitive#statusline()}

"display a warning if &et is wrong, or we have mixed-indenting
set statusline+=%#error#
set statusline+=%{StatuslineTabWarning()}
set statusline+=%*

set statusline+=%{StatuslineTrailingSpaceWarning()}

set statusline+=%{StatuslineLongLineWarning()}

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

"display a warning if &paste is set
set statusline+=%#error#
set statusline+=%{&paste?'[paste]':''}
set statusline+=%*

set statusline+=%=      "left/right separator
set statusline+=%{StatuslineCurrentHighlight()}\ \ "current highlight
set statusline+=%c,     "cursor column
set statusline+=%l/%L   "cursor line/total lines
set statusline+=\ %P    "percent through file
set laststatus=2

"print only to command bar
let g:bufferline_echo = 0

"no default mode indic
set noshowmode

"status line good fill chars
set fillchars+=stl:\ ,stlnc:\

"powerline symbols for the statusline
let g:airline_powerline_fonts = 1

"airline theme
let g:airline_theme='solarized'

"font symbols from powerline and fontconfig
if !exists('g:airline_symbols')
      let g:airline_symbols = {}
  endif
  let g:airline_symbols.space = "\ua0"

"recalculate the trailing whitespace warning when idle, and after saving
autocmd cursorhold,bufwritepost * unlet! b:statusline_trailing_space_warning

"return '[\s]' if trailing white space is detected
"return '' otherwise
function! StatuslineTrailingSpaceWarning()
    if !exists("b:statusline_trailing_space_warning")

        if !&modifiable
            let b:statusline_trailing_space_warning = ''
            return b:statusline_trailing_space_warning
        endif

        if search('\s\+$', 'nw') != 0
            let b:statusline_trailing_space_warning = '[\s]'
        else
            let b:statusline_trailing_space_warning = ''
        endif
    endif
    return b:statusline_trailing_space_warning
endfunction


"return the syntax highlight group under the cursor ''
function! StatuslineCurrentHighlight()
    let name = synIDattr(synID(line('.'),col('.'),1),'name')
    if name == ''
        return ''
    else
        return '[' . name . ']'
    endif
endfunction

"recalculate the tab warning flag when idle and after writing
autocmd cursorhold,bufwritepost * unlet! b:statusline_tab_warning

"return '[&et]' if &et is set wrong
"return '[mixed-indenting]' if spaces and tabs are used to indent
"return an empty string if everything is fine
function! StatuslineTabWarning()
    if !exists("b:statusline_tab_warning")
        let b:statusline_tab_warning = ''

        if !&modifiable
            return b:statusline_tab_warning
        endif

        let tabs = search('^\t', 'nw') != 0

        "find spaces that arent used as alignment in the first indent column
        let spaces = search('^ \{' . &ts . ',}[^\t]', 'nw') != 0

        if tabs && spaces
            let b:statusline_tab_warning =  '[mixed-indenting]'
        elseif (spaces && !&et) || (tabs && &et)
            let b:statusline_tab_warning = '[&et]'
        endif
    endif
    return b:statusline_tab_warning
endfunction

"recalculate the long line warning when idle and after saving
autocmd cursorhold,bufwritepost * unlet! b:statusline_long_line_warning

"return a warning for "long lines" where "long" is either &textwidth or 80 (if
"no &textwidth is set)
"
"return '' if no long lines
"return '[#x,my,$z] if long lines are found, were x is the number of long
"lines, y is the median length of the long lines and z is the length of the
"longest line
function! StatuslineLongLineWarning()
    if !exists("b:statusline_long_line_warning")

        if !&modifiable
            let b:statusline_long_line_warning = ''
            return b:statusline_long_line_warning
        endif

        let long_line_lens = s:LongLines()

        if len(long_line_lens) > 0
            let b:statusline_long_line_warning = "[" .
                        \ '#' . len(long_line_lens) . "," .
                        \ 'm' . s:Median(long_line_lens) . "," .
                        \ '$' . max(long_line_lens) . "]"
        else
            let b:statusline_long_line_warning = ""
        endif
    endif
    return b:statusline_long_line_warning
endfunction

"return a list containing the lengths of the long lines in this buffer
function! s:LongLines()
    let threshold = (&tw ? &tw : 80)
    let spaces = repeat(" ", &ts)
    let line_lens = map(getline(1,'$'), 'len(substitute(v:val, "\\t<smb://t>", spaces, "g"))')
    return filter(line_lens, 'v:val > threshold')
endfunction

"find the median of the given array of numbers
function! s:Median(nums)
    let nums = sort(a:nums)
    let l = len(nums)

    if l % 2 == 1
        let i = (l-1) / 2
        return nums[i]
    else
        return (nums[l/2] + nums[(l/2)-1]) / 2
    endif
endfunction

"nerdtree settings
let g:NERDTreeMouseMode = 2
let g:NERDTreeWinSize = 40

"explorer mappings
nnoremap <f1> :BufExplorer<cr>
nnoremap <f2> :NERDTreeToggle<cr>
nnoremap <f3> :TagbarToggle<cr>

"source project specific config files
runtime! projects/**/*.vim

"dont load csapprox if we no gui support - silences an annoying warning
if !has("gui")
    let g:CSApprox_loaded = 1
endif

"make <c-l> clear the highlight as well as redraw
nnoremap <C-L> :nohls<CR><C-L>
inoremap <C-L> <C-O>:nohls<CR>

"map Q to something useful
noremap Q gq

"make Y consistent with C and D
nnoremap Y y$

"visual search mappings
function! s:VSetSearch()
    let temp = @@
    norm! gvy
    let @/ = '\V' . substitute(escape(@@, '\'), '\n', '\\n'<smb://n'>, 'g')
    let @@ = temp
endfunction
vnoremap * :<C-u>call <SID>VSetSearch()<CR>//<CR>
vnoremap # :<C-u>call <SID>VSetSearch()<CR>??<CR>


"jump to last cursor position when opening a file
"dont do it when writing a commit log entry
autocmd BufReadPost * call SetCursorPosition()
function! SetCursorPosition()
    if &filetype !~ 'svn\|commit\c'
        if line("'\"") > 0 && line("'\"") <= line("$")
            exe "normal! g`\""
            normal! zz
        endif
    end
endfunction

"spell check when writing commit logs
autocmd filetype svn,*commit* setlocal spell

"http://vimcasts.org/episodes/fugitive-vim-browsing-the-git-object-database/
"hacks from above (the url, not jesus) to delete fugitive buffers when we
"leave them - otherwise the buffer list gets poluted
"
"add a mapping on .. to view parent tree
autocmd BufReadPost fugitive://* set bufhidden=delete
autocmd BufReadPost fugitive://*
  \ if fugitive#buffer().type() =~# '^\%(tree\|blob\)$' |
  \   nnoremap <buffer> .. :edit %:h<CR> |
  \ endif

"paredit
let g:paredit_leader = '\'

"mapping for date
:nnoremap <F9> "=strftime("%c")<CR>P
:inoremap <F9> <C-R>=strftime("%c")<CR>

"dotoo org/agenda

let g:dotoo#agenda#files = [ '~/logs/org/*.dotoo' ]
let g:dotoo#capture#refile = expand( '~/logs/org/refile.dotoo' )


Hans Anderson, Advanced Technology, ESPN




On Mar 24, 2015, at 9:05 AM, Dhruva Sagar <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't reproduce this, I am able to use colons in the capture text. Kindly provide more information.

**Comment by dhruvasagar** [comment] 2015-03-25 15:18
Would it be possible to make a small gif / video of the behavior ? I am not sure I actually understand what the problem is in the first place.

**Comment by dhruvasagar** [comment] 2015-08-18 08:41
Hi,

Since I was unable to reproduce / full understand the exact problem I am going to close this issue for the moment, kindly feel free to reopen it and provide more information to help me understand the problem better so I could reproduce it and then eventually fix it.

**Comment by kadadot216** [comment] 2020-07-29 17:21
I am reviving this thread because I have a similar issue using colons in capture mode/in an entry.

If an entry has colons in its description, it doesn't appear at all in the view.

How to reproduce:

* Add `* TODO meetup with Jane @10:30` (In capture tool / Directly edit dotoo file)
* Switch to Todo View `gAt`

Expected:

* Todo View shows TODO item

Result:

* Item is absent from Todo View

**Comment by dhruvasagar** [comment] 2020-07-29 19:22
@kadadot216 Thanks for raising this, I am now able to reproduce this issue.
This is going to be pretty hard to fix in the current parser implementation which is a crude regex based approach.

**Comment by dhruvasagar** [comment] 2021-05-22 12:00
@kadadot216 I have fixed this in a recent update with #125.

**Closed by dhruvasagar** 2021-05-22 12:00 UTC
