### ISSUE TITLE
Incorrect Clock Time

### ISSUE THREAD

**Issue by am2605** [dhruvasagar/vim-dotoo#40] opened 2016-11-07 03:21 UTC
I believe I've hit an issue similar to #15 

Whenever I clock in or clock out the date is set to 

[1970-01-01 Thu 11:00]--[1970-01-01 Thu 11:00]

I'm on Windows 10 and my Timezone is Australian Eastern Summer Time, which I suspect could be contributing factor(?).

Any suggestions on how I can correct this?

Thanks!

**Comment by dhruvasagar** [comment] 2016-11-07 04:23
Hi,

I will need to have a look into this, it is most likely a timezone issue, it's hard to deal with this completely however I can have a look into it. What is ur locale ? Sometimes that can have an impact, it did for #15.

**Comment by dhruvasagar** [comment] 2016-11-07 04:29
Can you tell me the output of `echo dotoo#time#new().to_string()`?
Also `echo strftime('%Y-%m-%d %H:%M', localtime())`

**Comment by am2605** [comment] 2016-11-07 05:39
Thanks for getting back to me.

My locale in Windows Control Panel is set to English(Australia).  Is that what you're after?  

Output of 

echo dotoo#time#new().to_string()

is

1970-01-01 Thu 11:00

Output of echo strftime('%Y-%m-%d %H:%M', localtime())

2016-11-07 16:38

If there's something else let me know.  Thanks again!

**Comment by paretje** [comment] 2016-11-07 13:37
What's the output of: `echo dotoo#time#new().datetime`?

**Comment by am2605** [comment] 2016-11-07 22:21
@paretje - here is the output 

`{'stzoffset': 39600, 'day': 1, 'htzoffset': 11, 'repeat': '', 'minute': 0, 'depoch': 0, 'sepoch': 0, 'year': 1970, 'month': 1, 'to_seconds': function('3'), 'second': 0, 'hour': 11, 'mtzoffset': 660}`

**Comment by dhruvasagar** [comment] 2016-11-08 09:57
I am not entirely sure if this would fix it since I cannot reproduce it reliably myself. Let me know.

**Comment by am2605** [comment] 2016-11-08 10:23
Thanks for this.  This has definitely made some progress, because the output of echo dotoo#time#new().datetime now looks correct compared to what it did before this change:

`{'stzoffset': 39600, 'day': 8, 'htzoffset': 11, 'repeat': '', 'minute': 19, 'depoch': 17113, 'sepoch': 0, 'year': 2016, 'month': 11, 'to_seconds': function('3'), 'second': 43, 'hour': 21, 'mtzoffset': 660}`

However the logbook is still showing the time as 1970:

```
:LOGBOOK:
CLOCK: [1970-01-01 Thu 11:00]--[1970-01-01 Thu 11:00] => 11:00
:END:

```

**Comment by dhruvasagar** [comment] 2016-11-08 10:30
That's good news, however the logbook entries aren't `refreshed` as such, moreover, in this context there isn't any way to fix the already wrongly captured date / time since there is no way to recover the original correct date / time it was meant to capture.

So you'll have to fix these dates manually, or remove them if you don't remember the right value.

**Comment by am2605** [comment] 2016-11-08 10:36
I understand that, however these were new entries on a completely new sheet.   So it seems although the output of `echo dotoo#time#new().datetime` has changed, whatever is being written to the logbook entry section is still 1970-01-01?

I just checked `echo dotoo#time#new().to_string()` and it still gives `1970-01-01 Thu 11:00`

**Comment by dhruvasagar** [comment] 2016-11-08 10:47
Oh, I didn't realise that. 

Can you tell me the output of `echo dotoo#time#new().to_seconds()` ?

**Comment by am2605** [comment] 2016-11-08 10:49
No problems, I wasn't very clear myself.

`echo dotoo#time#new().to_seconds()`

gives

`0`

**Comment by dhruvasagar** [comment] 2016-11-08 10:49
Also the output of `echo strftime('%s', localtime())`

**Comment by am2605** [comment] 2016-11-08 10:56
`echo strftime('%s', localtime())`

This seems to return an empty string?  (I'm typing it as `:echo strftime('%s', localtime())` and when I press enter the cmdline goes blank. (This is on Windows 10, gvim 7.4)

Just out of interest I tried that on a linux box I have access to (it doesn't have vim-dotoo installed though - yet ;-) ) and it returned `1478602467 ` so I think this could be some kind of windows weirdness :(  Makes me wonder if it's something I should log with VIM?

**Comment by dhruvasagar** [comment] 2016-11-08 10:59
Yes, that's the source of the problem. `strftime()` which I use for time formatting / parsing, it's documentation does state that it is not platform agnostic and so need to refer to the API doc of the 'c' API. Will have further look into it, I suppose I have to use some different format than '%s' to get the unix time on windows.

**Comment by am2605** [comment] 2016-11-08 11:11
Okay that makes sense.  Obviously if I'm the only windows user I wouldn't expect you to spend too much time on this, but if you do want to persue it I'm happy to keep helping.

**Comment by dhruvasagar** [comment] 2016-11-08 11:13
Thanks for that, now that we know the source of the problem I should be able to figure out a work around for windows. Will take sometime though, will look deeper when I have more time.

**Comment by am2605** [comment] 2016-11-08 11:17
No problems at all.  I appreciate it!

**Comment by mitnworb** [comment] 2017-05-10 16:25
I am having a similar issue to am2605.  My agenda files have current date, but they show up many, many years in the past.  When I run echo strftime('%s', localtime()) is show some number like 1494433389.  I am running it on Antergos linux.

**Comment by dhruvasagar** [comment] 2017-05-11 06:08
This is hard to investigate without being able to reproduce myself. I think i'll write a test script specifically to capture inconsistencies with respect to time parsing and share.

**Comment by christianhaargaard** [comment] 2017-12-20 08:17
I'm also on windows, and managed to get correct time stamps by changing line 66 in autoload/dotoo/time.vim from
        \, 'sepoch' : +strftime('%s', ts)
to
        \, 'sepoch' : ts
.

**Comment by dhruvasagar** [comment] 2017-12-20 08:37
Looks like the +strftime format may not work on windows perhaps. I did play around with swapping them earlier but causes other issues

**Comment by christianhaargaard** [comment] 2017-12-20 09:23
My testing, and what I can read elsewhere, suggests that it is just the "%s" that isn't working.
I have not tested vim-dotoo a lot after making the change I suggest above, but so far it doesn't seem to be causing any problems.
As far as I understand the code is simply printing the unix-time (`ts`) in the format of unix-time when using `strftime("%s", ts)`. Is that correct? If so, shouldn't it be fine to just print `ts` directly?

**Comment by dhruvasagar** [comment] 2017-12-28 03:26
@christianhaargaard yes you are right in that the problem is with strftime, specifically for the '%s' format. i'll make this change and push it out. I am in the process of (since very long) writing tests but that's going to take a bit of time, so if there are issues please do let me know.

**Comment by dhruvasagar** [comment] 2020-06-02 18:12
I believe this is no more an issue and I have reverted the original fix to keep things simple. If this becomes an issue again we shall reopen this ticket.

**Comment by jmzagorski** [comment] 2020-06-23 00:11
I am guessing https://github.com/dhruvasagar/vim-dotoo/commit/1df4ba76b74981bb8a2e9dae6bfe9e241be1831f made the problem return on windows. Putting the change @christianhaargaard works. 

My echos:

`echo dotoo#time#new().to_string()`
1969-12-31 Wed 19:00

`echo strftime('%Y-%m-%d %H:%M', localtime())`
2020-06-22 20:09

`echo dotoo#time#new().datetime`
{'stzoffset': -14400, 'day': 22, 'htzoffset': -4, 'repeat': '', 'minute': 10, 'depoch': 18435, 'sepoch': 0, 'year': 2020, 'month': 6, 'to_seconds': function('1'), 'second': 7, 'hour': 20, 'mtzoffset': -240}

`echo dotoo#time#new().to_seconds() `
0

`echo strftime('%s', localtime())`
empty string

**Comment by dhruvasagar** [comment] 2020-06-23 01:51
That's not good. Kindly share your vim version and locale settings

**Comment by jmzagorski** [comment] 2020-06-23 02:32
Thanks for the reply. Let me know if you need anything else.

**vim**
v8.2 patch 1-981, using gvim on windows.

**locale**
English(United States)

**Comment by dhruvasagar** [comment] 2020-07-20 13:20
@am2605 @jmzagorski I have pushed a fix that should fix this.

**Comment by barmatal** [comment] 2020-07-21 15:58
The fix worked for me. Thanks!

**Closed** 2020-07-21 16:33 UTC
